package com.cronos.modelo;
// Generated 18/07/2016 11:18:04 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * P00departamento generated by hbm2java
 */
public class P00departamento  implements java.io.Serializable {


     private Integer iddepartamento;
     private String departamento;
     private String nombre;
     private Set<P00municipio> p00municipios = new HashSet<P00municipio>(0);

    public P00departamento() {
    }

	
    public P00departamento(Integer iddepartamento, String departamento, String nombre) {
        this.iddepartamento = iddepartamento;
        this.departamento = departamento;
        this.nombre = nombre;
    }
    public P00departamento(Integer iddepartamento, String departamento, String nombre, Set<P00municipio> p00municipios) {
       this.iddepartamento = iddepartamento;
       this.departamento = departamento;
       this.nombre = nombre;
       this.p00municipios = p00municipios;
    }
   
    public Integer getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(Integer iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<P00municipio> getP00municipios() {
        return this.p00municipios;
    }
    
    public void setP00municipios(Set<P00municipio> p00municipios) {
        this.p00municipios = p00municipios;
    }




}


