package com.cronos.modelo;
// Generated 6/07/2016 09:47:47 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * P00listaopcion generated by hbm2java
 */
public class P00listaopcion  implements java.io.Serializable {


     private Integer rowidopcion;
     private String variable;
     private String descripcion;
     private Integer valor;
     private String nombre;
     private String abreviacion;
     private String condicion;
     private Boolean habilita;
     private String validacion;
     private Set<P10clientes> p10clientesesForRowidtipoidentificacion = new HashSet<P10clientes>(0);
     private Set<P10clientes> p10clientesesForRowidtipocliente = new HashSet<P10clientes>(0);
     private Set<P10clientes> p10clientesesForRowidsexo = new HashSet<P10clientes>(0);
     private Set<P10clientes> p10clientesesForRowidestadocivil = new HashSet<P10clientes>(0);
     private Set<P10clientes> p10clientesesForRowidtipoprofesion = new HashSet<P10clientes>(0);

    public P00listaopcion() {
    }

	
    public P00listaopcion(Integer rowidopcion, String variable, String descripcion, Integer valor, String nombre, Boolean habilita, String validacion) {
        this.rowidopcion = rowidopcion;
        this.variable = variable;
        this.descripcion = descripcion;
        this.valor = valor;
        this.nombre = nombre;
        this.habilita = habilita;
        this.validacion = validacion;
    }
    public P00listaopcion(Integer rowidopcion, String variable, String descripcion, Integer valor, String nombre, String abreviacion, String condicion, Boolean habilita, String validacion, Set<P10clientes> p10clientesesForRowidtipoidentificacion, Set<P10clientes> p10clientesesForRowidtipocliente, Set<P10clientes> p10clientesesForRowidsexo, Set<P10clientes> p10clientesesForRowidestadocivil, Set<P10clientes> p10clientesesForRowidtipoprofesion) {
       this.rowidopcion = rowidopcion;
       this.variable = variable;
       this.descripcion = descripcion;
       this.valor = valor;
       this.nombre = nombre;
       this.abreviacion = abreviacion;
       this.condicion = condicion;
       this.habilita = habilita;
       this.validacion = validacion;
       this.p10clientesesForRowidtipoidentificacion = p10clientesesForRowidtipoidentificacion;
       this.p10clientesesForRowidtipocliente = p10clientesesForRowidtipocliente;
       this.p10clientesesForRowidsexo = p10clientesesForRowidsexo;
       this.p10clientesesForRowidestadocivil = p10clientesesForRowidestadocivil;
       this.p10clientesesForRowidtipoprofesion = p10clientesesForRowidtipoprofesion;
    }
   
    public Integer getRowidopcion() {
        return this.rowidopcion;
    }
    
    public void setRowidopcion(Integer rowidopcion) {
        this.rowidopcion = rowidopcion;
    }
    public String getVariable() {
        return this.variable;
    }
    
    public void setVariable(String variable) {
        this.variable = variable;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviacion() {
        return this.abreviacion;
    }
    
    public void setAbreviacion(String abreviacion) {
        this.abreviacion = abreviacion;
    }
    public String getCondicion() {
        return this.condicion;
    }
    
    public void setCondicion(String condicion) {
        this.condicion = condicion;
    }
    public Boolean getHabilita() {
        return this.habilita;
    }
    
    public void setHabilita(Boolean habilita) {
        this.habilita = habilita;
    }
    public String getValidacion() {
        return this.validacion;
    }
    
    public void setValidacion(String validacion) {
        this.validacion = validacion;
    }
    public Set<P10clientes> getP10clientesesForRowidtipoidentificacion() {
        return this.p10clientesesForRowidtipoidentificacion;
    }
    
    public void setP10clientesesForRowidtipoidentificacion(Set<P10clientes> p10clientesesForRowidtipoidentificacion) {
        this.p10clientesesForRowidtipoidentificacion = p10clientesesForRowidtipoidentificacion;
    }
    public Set<P10clientes> getP10clientesesForRowidtipocliente() {
        return this.p10clientesesForRowidtipocliente;
    }
    
    public void setP10clientesesForRowidtipocliente(Set<P10clientes> p10clientesesForRowidtipocliente) {
        this.p10clientesesForRowidtipocliente = p10clientesesForRowidtipocliente;
    }
    public Set<P10clientes> getP10clientesesForRowidsexo() {
        return this.p10clientesesForRowidsexo;
    }
    
    public void setP10clientesesForRowidsexo(Set<P10clientes> p10clientesesForRowidsexo) {
        this.p10clientesesForRowidsexo = p10clientesesForRowidsexo;
    }
    public Set<P10clientes> getP10clientesesForRowidestadocivil() {
        return this.p10clientesesForRowidestadocivil;
    }
    
    public void setP10clientesesForRowidestadocivil(Set<P10clientes> p10clientesesForRowidestadocivil) {
        this.p10clientesesForRowidestadocivil = p10clientesesForRowidestadocivil;
    }
    public Set<P10clientes> getP10clientesesForRowidtipoprofesion() {
        return this.p10clientesesForRowidtipoprofesion;
    }
    
    public void setP10clientesesForRowidtipoprofesion(Set<P10clientes> p10clientesesForRowidtipoprofesion) {
        this.p10clientesesForRowidtipoprofesion = p10clientesesForRowidtipoprofesion;
    }




}


