package com.cronos.modelo;
// Generated 18/07/2016 11:18:04 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * P00municipio generated by hbm2java
 */
public class P00municipio  implements java.io.Serializable {


     private Integer idmunicipio;
     private P00departamento p00departamento;
     private String municipio;
     private String nombre;
     private Set<P10clientes> p10clienteses = new HashSet<P10clientes>(0);

    public P00municipio() {
    }

	
    public P00municipio(Integer idmunicipio, P00departamento p00departamento, String municipio, String nombre) {
        this.idmunicipio = idmunicipio;
        this.p00departamento = p00departamento;
        this.municipio = municipio;
        this.nombre = nombre;
    }
    public P00municipio(Integer idmunicipio, P00departamento p00departamento, String municipio, String nombre, Set<P10clientes> p10clienteses) {
       this.idmunicipio = idmunicipio;
       this.p00departamento = p00departamento;
       this.municipio = municipio;
       this.nombre = nombre;
       this.p10clienteses = p10clienteses;
    }
   
    public Integer getIdmunicipio() {
        return this.idmunicipio;
    }
    
    public void setIdmunicipio(Integer idmunicipio) {
        this.idmunicipio = idmunicipio;
    }
    public P00departamento getP00departamento() {
        return this.p00departamento;
    }
    
    public void setP00departamento(P00departamento p00departamento) {
        this.p00departamento = p00departamento;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<P10clientes> getP10clienteses() {
        return this.p10clienteses;
    }
    
    public void setP10clienteses(Set<P10clientes> p10clienteses) {
        this.p10clienteses = p10clienteses;
    }




}


