package com.cronos.modelo;
// Generated 6/07/2016 09:47:47 AM by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * P00perfil generated by hbm2java
 */
public class P00perfil  implements java.io.Serializable {


     private Integer rowidperfil;
     private P00empresa p00empresa;
     private String perfil;
     private String nombre;
     private Integer diasvigencia;
     private Boolean habilita;
     private Set<P00perfilmenu> p00perfilmenus = new HashSet<P00perfilmenu>(0);
     private Set<P00usuario> p00usuarios = new HashSet<P00usuario>(0);

    public P00perfil() {
    }

	
    public P00perfil(Integer rowidperfil, P00empresa p00empresa, String perfil, String nombre, Integer diasvigencia, Boolean habilita) {
        this.rowidperfil = rowidperfil;
        this.p00empresa = p00empresa;
        this.perfil = perfil;
        this.nombre = nombre;
        this.diasvigencia = diasvigencia;
        this.habilita = habilita;
    }
    public P00perfil(Integer rowidperfil, P00empresa p00empresa, String perfil, String nombre, Integer diasvigencia, Boolean habilita, Set<P00perfilmenu> p00perfilmenus, Set<P00usuario> p00usuarios) {
       this.rowidperfil = rowidperfil;
       this.p00empresa = p00empresa;
       this.perfil = perfil;
       this.nombre = nombre;
       this.diasvigencia = diasvigencia;
       this.habilita = habilita;
       this.p00perfilmenus = p00perfilmenus;
       this.p00usuarios = p00usuarios;
    }
   
    public Integer getRowidperfil() {
        return this.rowidperfil;
    }
    
    public void setRowidperfil(Integer rowidperfil) {
        this.rowidperfil = rowidperfil;
    }
    public P00empresa getP00empresa() {
        return this.p00empresa;
    }
    
    public void setP00empresa(P00empresa p00empresa) {
        this.p00empresa = p00empresa;
    }
    public String getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getDiasvigencia() {
        return this.diasvigencia;
    }
    
    public void setDiasvigencia(Integer diasvigencia) {
        this.diasvigencia = diasvigencia;
    }
    public Boolean getHabilita() {
        return this.habilita;
    }
    
    public void setHabilita(Boolean habilita) {
        this.habilita = habilita;
    }
    public Set<P00perfilmenu> getP00perfilmenus() {
        return this.p00perfilmenus;
    }
    
    public void setP00perfilmenus(Set<P00perfilmenu> p00perfilmenus) {
        this.p00perfilmenus = p00perfilmenus;
    }
    public Set<P00usuario> getP00usuarios() {
        return this.p00usuarios;
    }
    
    public void setP00usuarios(Set<P00usuario> p00usuarios) {
        this.p00usuarios = p00usuarios;
    }




}


