package com.cronos.modelo;
// Generated 6/07/2016 09:47:47 AM by Hibernate Tools 4.3.1.Final



/**
 * P00perfilmenu generated by hbm2java
 */
public class P00perfilmenu  implements java.io.Serializable {


     private Integer rowidperfilmenu;
     private P00menu p00menu;
     private P00perfil p00perfil;

    public P00perfilmenu() {
    }

    public P00perfilmenu(Integer rowidperfilmenu, P00menu p00menu, P00perfil p00perfil) {
       this.rowidperfilmenu = rowidperfilmenu;
       this.p00menu = p00menu;
       this.p00perfil = p00perfil;
    }
   
    public Integer getRowidperfilmenu() {
        return this.rowidperfilmenu;
    }
    
    public void setRowidperfilmenu(Integer rowidperfilmenu) {
        this.rowidperfilmenu = rowidperfilmenu;
    }
    public P00menu getP00menu() {
        return this.p00menu;
    }
    
    public void setP00menu(P00menu p00menu) {
        this.p00menu = p00menu;
    }
    public P00perfil getP00perfil() {
        return this.p00perfil;
    }
    
    public void setP00perfil(P00perfil p00perfil) {
        this.p00perfil = p00perfil;
    }




}


