package com.cronos.modelo;
// Generated 6/07/2016 09:47:47 AM by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * P10clientes generated by hbm2java
 */
public class P10clientes  implements java.io.Serializable {


    private Integer rowidcliente;
    private P00empresa p00empresa;
    private P00listaopcion p00listaopcionByRowidtipoidentificacion;
    private P00listaopcion p00listaopcionByRowidtipocliente;
    private P00listaopcion p00listaopcionByRowidsexo;
    private P00listaopcion p00listaopcionByRowidestadocivil;
    private P00listaopcion p00listaopcionByRowidtipoprofesion;
    private P00municipio p00municipio;
    private String numeroidentificacion;
    private String digitoverificacion;
    private String razonsocial;
    private String nombres;
    private String apellidos;
    private Date fechanacimiento;
    private String direccion;
    private String telefono;
    private String correopersonal;
    private Boolean tienehijos;
    private String descripcionprofesion;
    private String empresalabora;
    private String direccionempresa;
    private String telefonoempresa;
    private Boolean habilita;
    private String celular;
    private String correoinstitucional;
    private Integer cantidadhijos;
    private Integer titularvivienda;
    private Set<P10vehiculos> p10vehiculoses = new HashSet<P10vehiculos>(0);
    private Set<P10soat> p10soats = new HashSet<P10soat>(0);

   public P10clientes() {
   }

	
   public P10clientes(Integer rowidcliente, P00empresa p00empresa, P00listaopcion p00listaopcionByRowidtipoidentificacion, P00listaopcion p00listaopcionByRowidtipocliente, P00listaopcion p00listaopcionByRowidsexo, P00listaopcion p00listaopcionByRowidtipoprofesion, String numeroidentificacion, String digitoverificacion, String nombres, String apellidos, Boolean tienehijos, Boolean habilita) {
       this.rowidcliente = rowidcliente;
       this.p00empresa = p00empresa;
       this.p00listaopcionByRowidtipoidentificacion = p00listaopcionByRowidtipoidentificacion;
       this.p00listaopcionByRowidtipocliente = p00listaopcionByRowidtipocliente;
       this.p00listaopcionByRowidsexo = p00listaopcionByRowidsexo;
       this.p00listaopcionByRowidtipoprofesion = p00listaopcionByRowidtipoprofesion;
       this.numeroidentificacion = numeroidentificacion;
       this.digitoverificacion = digitoverificacion;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.tienehijos = tienehijos;
       this.habilita = habilita;
   }
  
   public Integer getRowidcliente() {
       return this.rowidcliente;
   }
   
   public void setRowidcliente(Integer rowidcliente) {
       this.rowidcliente = rowidcliente;
   }
   public P00empresa getP00empresa() {
       return this.p00empresa;
   }
   
   public void setP00empresa(P00empresa p00empresa) {
       this.p00empresa = p00empresa;
   }
   public P00listaopcion getP00listaopcionByRowidtipoidentificacion() {
       return this.p00listaopcionByRowidtipoidentificacion;
   }
   
   public void setP00listaopcionByRowidtipoidentificacion(P00listaopcion p00listaopcionByRowidtipoidentificacion) {
       this.p00listaopcionByRowidtipoidentificacion = p00listaopcionByRowidtipoidentificacion;
   }
   public P00listaopcion getP00listaopcionByRowidtipocliente() {
       return this.p00listaopcionByRowidtipocliente;
   }
   
   public void setP00listaopcionByRowidtipocliente(P00listaopcion p00listaopcionByRowidtipocliente) {
       this.p00listaopcionByRowidtipocliente = p00listaopcionByRowidtipocliente;
   }
   public P00listaopcion getP00listaopcionByRowidsexo() {
       return this.p00listaopcionByRowidsexo;
   }
   
   public void setP00listaopcionByRowidsexo(P00listaopcion p00listaopcionByRowidsexo) {
       this.p00listaopcionByRowidsexo = p00listaopcionByRowidsexo;
   }
   public P00listaopcion getP00listaopcionByRowidestadocivil() {
       return this.p00listaopcionByRowidestadocivil;
   }
   
   public void setP00listaopcionByRowidestadocivil(P00listaopcion p00listaopcionByRowidestadocivil) {
       this.p00listaopcionByRowidestadocivil = p00listaopcionByRowidestadocivil;
   }
   public P00listaopcion getP00listaopcionByRowidtipoprofesion() {
       return this.p00listaopcionByRowidtipoprofesion;
   }
   
   public void setP00listaopcionByRowidtipoprofesion(P00listaopcion p00listaopcionByRowidtipoprofesion) {
       this.p00listaopcionByRowidtipoprofesion = p00listaopcionByRowidtipoprofesion;
   }
   public P00municipio getP00municipio() {
       return this.p00municipio;
   }
   
   public void setP00municipio(P00municipio p00municipio) {
       this.p00municipio = p00municipio;
   }
   public String getNumeroidentificacion() {
       return this.numeroidentificacion;
   }
   
   public void setNumeroidentificacion(String numeroidentificacion) {
       this.numeroidentificacion = numeroidentificacion;
   }
   public String getDigitoverificacion() {
       return this.digitoverificacion;
   }
   
   public void setDigitoverificacion(String digitoverificacion) {
       this.digitoverificacion = digitoverificacion;
   }
   public String getRazonsocial() {
       return this.razonsocial;
   }
   
   public void setRazonsocial(String razonsocial) {
       this.razonsocial = razonsocial;
   }
   public String getNombres() {
       return this.nombres;
   }
   
   public void setNombres(String nombres) {
       this.nombres = nombres;
   }
   public String getApellidos() {
       return this.apellidos;
   }
   
   public void setApellidos(String apellidos) {
       this.apellidos = apellidos;
   }
   public Date getFechanacimiento() {
       return this.fechanacimiento;
   }
   
   public void setFechanacimiento(Date fechanacimiento) {
       this.fechanacimiento = fechanacimiento;
   }
   public String getDireccion() {
       return this.direccion;
   }
   
   public void setDireccion(String direccion) {
       this.direccion = direccion;
   }
   public String getTelefono() {
       return this.telefono;
   }
   
   public void setTelefono(String telefono) {
       this.telefono = telefono;
   }
   public String getCorreopersonal() {
       return this.correopersonal;
   }
   
   public void setCorreopersonal(String correopersonal) {
       this.correopersonal = correopersonal;
   }
   public Boolean getTienehijos() {
       return this.tienehijos;
   }
   
   public void setTienehijos(Boolean tienehijos) {
       this.tienehijos = tienehijos;
   }
   public String getDescripcionprofesion() {
       return this.descripcionprofesion;
   }
   
   public void setDescripcionprofesion(String descripcionprofesion) {
       this.descripcionprofesion = descripcionprofesion;
   }
   public String getEmpresalabora() {
       return this.empresalabora;
   }
   
   public void setEmpresalabora(String empresalabora) {
       this.empresalabora = empresalabora;
   }
   public String getDireccionempresa() {
       return this.direccionempresa;
   }
   
   public void setDireccionempresa(String direccionempresa) {
       this.direccionempresa = direccionempresa;
   }
   public String getTelefonoempresa() {
       return this.telefonoempresa;
   }
   
   public void setTelefonoempresa(String telefonoempresa) {
       this.telefonoempresa = telefonoempresa;
   }
   public Boolean getHabilita() {
       return this.habilita;
   }
   
   public void setHabilita(Boolean habilita) {
       this.habilita = habilita;
   }
   public String getCelular() {
       return this.celular;
   }
   
   public void setCelular(String celular) {
       this.celular = celular;
   }
   public String getCorreoinstitucional() {
       return this.correoinstitucional;
   }
   
   public void setCorreoinstitucional(String correoinstitucional) {
       this.correoinstitucional = correoinstitucional;
   }
   public Integer getCantidadhijos() {
       return this.cantidadhijos;
   }
   
   public void setCantidadhijos(Integer cantidadhijos) {
       this.cantidadhijos = cantidadhijos;
   }
   public Integer getTitularvivienda() {
       return this.titularvivienda;
   }
   
   public void setTitularvivienda(Integer titularvivienda) {
       this.titularvivienda = titularvivienda;
   }


	public Set<P10vehiculos> getP10vehiculoses() {
		return p10vehiculoses;
	}
	
	
	public void setP10vehiculoses(Set<P10vehiculos> p10vehiculoses) {
		this.p10vehiculoses = p10vehiculoses;
	}
	
	
	public Set<P10soat> getP10soats() {
		return p10soats;
	}
	
	
	public void setP10soats(Set<P10soat> p10soats) {
		this.p10soats = p10soats;
	}
}
