package com.cronos.modelo;
// Generated 27/07/2016 02:29:17 PM by Hibernate Tools 4.3.1.Final


import java.util.Date;

/**
 * P10soat generated by hbm2java
 */
public class P10soat  implements java.io.Serializable {


     private Integer rowidsoat;
     private P10clientes p10clientes;
     private P10vehiculos p10vehiculos;
     private Boolean habilita;
     private Date fechaexpedicion;
     private Date fechainiciovigencia;
     private String observaciones;

    public P10soat() {
    }

    public P10soat(Integer rowidsoat, P10clientes p10clientes, P10vehiculos p10vehiculos, Boolean habilita, Date fechaexpedicion, Date fechainiciovigencia) {
       this.rowidsoat = rowidsoat;
       this.p10clientes = p10clientes;
       this.p10vehiculos = p10vehiculos;
       this.habilita = habilita;
       this.fechaexpedicion = fechaexpedicion;
       this.fechainiciovigencia = fechainiciovigencia;
    }
   
    public Integer getRowidsoat() {
        return this.rowidsoat;
    }
    
    public void setRowidsoat(Integer rowidsoat) {
        this.rowidsoat = rowidsoat;
    }
    public P10clientes getP10clientes() {
        return this.p10clientes;
    }
    
    public void setP10clientes(P10clientes p10clientes) {
        this.p10clientes = p10clientes;
    }
    public P10vehiculos getP10vehiculos() {
        return this.p10vehiculos;
    }
    
    public void setP10vehiculos(P10vehiculos p10vehiculos) {
        this.p10vehiculos = p10vehiculos;
    }
    public Boolean getHabilita() {
        return this.habilita;
    }
    
    public void setHabilita(Boolean habilita) {
        this.habilita = habilita;
    }
    public Date getFechaexpedicion() {
        return this.fechaexpedicion;
    }
    
    public void setFechaexpedicion(Date fechaexpedicion) {
        this.fechaexpedicion = fechaexpedicion;
    }
    public Date getFechainiciovigencia() {
        return this.fechainiciovigencia;
    }
    
    public void setFechainiciovigencia(Date fechainiciovigencia) {
        this.fechainiciovigencia = fechainiciovigencia;
    }

	public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}


