package com.cronos.modelo;

import java.util.HashSet;
import java.util.Set;
// Generated 26/07/2016 12:42:39 PM by Hibernate Tools 4.3.1.Final



/**
 * P10vehiculos generated by hbm2java
 */
public class P10vehiculos  implements java.io.Serializable {


     private Integer rowidvehiculos;
     private P00empresa p00empresa;
     private P00listaopcion p00listaopcionByRowidclasevehiculo;
     private P00listaopcion p00listaopcionByRowidtiposervicio;
     private P10clientes p10clientes;
     private String numeroplaca;
     private String codigofasecolda;
     private String cilindraje;
     private String modelo;
     private String nropasajeros;
     private Integer capacidadtoneladas;
     private String nromotor;
     private String nrochasis;
     private Set<P10soat> p10soats = new HashSet<P10soat>(0);

    public P10vehiculos() {
    }

	
    public P10vehiculos(Integer rowidvehiculos, P00empresa p00empresa, P00listaopcion p00listaopcionByRowidclasevehiculo, P00listaopcion p00listaopcionByRowidtiposervicio, P10clientes p10clientes, String numeroplaca) {
        this.rowidvehiculos = rowidvehiculos;
        this.p00empresa = p00empresa;
        this.p00listaopcionByRowidclasevehiculo = p00listaopcionByRowidclasevehiculo;
        this.p00listaopcionByRowidtiposervicio = p00listaopcionByRowidtiposervicio;
        this.p10clientes = p10clientes;
        this.numeroplaca = numeroplaca;
    }
    public P10vehiculos(Integer rowidvehiculos, P00empresa p00empresa, P00listaopcion p00listaopcionByRowidclasevehiculo, P00listaopcion p00listaopcionByRowidtiposervicio, P10clientes p10clientes, String numeroplaca, String codigofasecolda, String cilindraje, String modelo, String nropasajeros, Integer capacidadtoneladas, String nromotor, String nrochasis) {
       this.rowidvehiculos = rowidvehiculos;
       this.p00empresa = p00empresa;
       this.p00listaopcionByRowidclasevehiculo = p00listaopcionByRowidclasevehiculo;
       this.p00listaopcionByRowidtiposervicio = p00listaopcionByRowidtiposervicio;
       this.p10clientes = p10clientes;
       this.numeroplaca = numeroplaca;
       this.codigofasecolda = codigofasecolda;
       this.cilindraje = cilindraje;
       this.modelo = modelo;
       this.nropasajeros = nropasajeros;
       this.capacidadtoneladas = capacidadtoneladas;
       this.nromotor = nromotor;
       this.nrochasis = nrochasis;
    }
   
    public Integer getRowidvehiculos() {
        return this.rowidvehiculos;
    }
    
    public void setRowidvehiculos(Integer rowidvehiculos) {
        this.rowidvehiculos = rowidvehiculos;
    }
    public P00empresa getP00empresa() {
        return this.p00empresa;
    }
    
    public void setP00empresa(P00empresa p00empresa) {
        this.p00empresa = p00empresa;
    }
    public P00listaopcion getP00listaopcionByRowidclasevehiculo() {
        return this.p00listaopcionByRowidclasevehiculo;
    }
    
    public void setP00listaopcionByRowidclasevehiculo(P00listaopcion p00listaopcionByRowidclasevehiculo) {
        this.p00listaopcionByRowidclasevehiculo = p00listaopcionByRowidclasevehiculo;
    }
    public P00listaopcion getP00listaopcionByRowidtiposervicio() {
        return this.p00listaopcionByRowidtiposervicio;
    }
    
    public void setP00listaopcionByRowidtiposervicio(P00listaopcion p00listaopcionByRowidtiposervicio) {
        this.p00listaopcionByRowidtiposervicio = p00listaopcionByRowidtiposervicio;
    }
    public P10clientes getP10clientes() {
        return this.p10clientes;
    }
    
    public void setP10clientes(P10clientes p10clientes) {
        this.p10clientes = p10clientes;
    }
    public String getNumeroplaca() {
        return this.numeroplaca;
    }
    
    public void setNumeroplaca(String numeroplaca) {
        this.numeroplaca = numeroplaca;
    }
    public String getCodigofasecolda() {
        return this.codigofasecolda;
    }
    
    public void setCodigofasecolda(String codigofasecolda) {
        this.codigofasecolda = codigofasecolda;
    }
    public String getCilindraje() {
        return this.cilindraje;
    }
    
    public void setCilindraje(String cilindraje) {
        this.cilindraje = cilindraje;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getNropasajeros() {
        return this.nropasajeros;
    }
    
    public void setNropasajeros(String nropasajeros) {
        this.nropasajeros = nropasajeros;
    }
    public Integer getCapacidadtoneladas() {
        return this.capacidadtoneladas;
    }
    
    public void setCapacidadtoneladas(Integer capacidadtoneladas) {
        this.capacidadtoneladas = capacidadtoneladas;
    }
    public String getNromotor() {
        return this.nromotor;
    }
    
    public void setNromotor(String nromotor) {
        this.nromotor = nromotor;
    }
    public String getNrochasis() {
        return this.nrochasis;
    }
    
    public void setNrochasis(String nrochasis) {
        this.nrochasis = nrochasis;
    }


	public Set<P10soat> getP10soats() {
		return p10soats;
	}


	public void setP10soats(Set<P10soat> p10soats) {
		this.p10soats = p10soats;
	}
}


